# File: 03_product_revenue_analysis.py
# Role: Analyze revenue generated by each product category.

import pandas as pd
from sqlalchemy import create_engine
import os

def analyze_revenue_by_category():
    """
    Connects to the DB, identifies the most profitable product categories,
    and displays the top 10.
    """
    db_name = 'olist.db'
    if not os.path.exists(db_name):
        print(f"Error: Database '{db_name}' not found.")
        print("Please run '01_create_database.py' first to create it.")
        return

    engine = create_engine(f'sqlite:///{db_name}')

    # This SQL query is more complex:
    # 1. It joins the order_items and products tables on their common key (product_id).
    # 2. It calculates the sum of prices (SUM(price)) for each category.
    # 3. It groups the results by category (GROUP BY).
    # 4. It sorts the results to show the most profitable first (ORDER BY ... DESC).
    # 5. It keeps only the top 10 (LIMIT 10).
    query = """
    SELECT
        p.product_category_name,
        SUM(oi.price) as total_revenue
    FROM
        order_items oi
    JOIN
        products p ON oi.product_id = p.product_id
    WHERE
        p.product_category_name IS NOT NULL -- Ignore products without a category
    GROUP BY
        p.product_category_name
    ORDER BY
        total_revenue DESC
    LIMIT 10;
    """

    print("--- Running analysis of revenue by product category ---")
    
    try:
        df_results = pd.read_sql_query(query, engine)
        
        # Format the revenue column to display as currency
        df_results['total_revenue'] = df_results['total_revenue'].map('R$ {:,.2f}'.format)

        print("\n✅ Top 10 product categories by revenue:")
        print(df_results.to_string())

    except Exception as e:
        print(f"An error occurred: {e}")


if __name__ == '__main__':
    analyze_revenue_by_category()